### ISSUE TITLE
ファイル名などをmanaに統一する

### ISSUE THREAD

**Issue by na2co3-ftw** [na2co3-ftw/manakonso#7]
ファイル名、変数名、クラス名などにcrvやcorvusやcorvusskkなどが残っていたらmanaに統一する。(corvusskkの場合manakonsoに)
その他のskkを含む名前はとりあえず保留。

**Comment by ryoh827** [comment]
すべてのプロジェクトについて変更を行いますか？

**Comment by na2co3-ftw** [comment]
まあ内部のコードの話なので何でもいいといえば何でもいいんですよね。
気分的に統一したいなーと思っただけなんだけど…面倒そうですね…

**Comment by na2co3-ftw** [comment]
一旦保留で。

**Comment by ryoh827** [comment]
わかりました。
