### ISSUE TITLE
SystemRootのconfigファイルを認識しない

### ISSUE THREAD

**Issue by na2co3-ftw** [na2co3-ftw/manakonso#9]
%SystemRoot%\IME\IMCRVSKK\config.xml にある、デフォルトの設定ファイルをimmanatipが認識しない。

**Comment by nathancorvussolis** [comment]
common/version.h で、
#define   TEXTSERVICE_DIR   L"IMMANASKK"
としているので、
imcrvtip/FnConfig.cpp の void CTextService::_CreateConfigPath() で
"%SystemRoot%\IME\IMMANASKK\config.xml" が生成されています。

**Comment by na2co3-ftw** [comment]
修正しました。ご指摘ありがとうございます。
あと最初の投稿でのIMCRVSKKはIMMANAKONSOの間違いでした。
